sudo: required
services: 
  - docker

before_install: 
  - docker build -t iccircuit/docker-react -f Dockerfile . 

script: 
  - docker run -e CI=true iccircuit/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-084440461990"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$access_key"
  secret_access_key: "$secret_key"
